# -*- coding: utf-8 -*-
"""
Created on Thu Jan 23 17:33:18 2020

@author: jupiter
"""

import os
import random
import mytype
import scorekeep
import asyncio
from PIL import Image
from vsimage import multi_imageconcat
import configparser

import discord
from dotenv import load_dotenv


load_dotenv()
token = os.getenv('DISCORD_TOKEN')

client = discord.Client()

@client.event
async def on_ready():
    print(f'{client.user.name} has connected to Discord!')  #Tells you the bot has connected properly
    activ = discord.Game('Nintendogs™')                     #Changes player activity to playing Nintendogs
    await client.change_presence(activity=activ)
    



@client.event
async def on_message(message):
    if message.author.bot:                                  #Keeps LeoBot from responding to bot messages
        return
        
    if message.content == '!myaesthetic':                   #generates aesthetic message on command !myaesthetic
        await message.channel.send('{} your aesthetic is {} {} {}.'.format(message.author.mention,*mytype.whataesthet()))
    
    if message.content == '!mytype':                        #generates type message on command !mytype
        urtype = mytype.whattype()
        if len(urtype) == 3:
            await message.channel.send('{} you are {} {} {} type!'.format(message.author.mention,*urtype))
        else:
            await message.channel.send('{} you are {} {} type!'.format(message.author.mention,*urtype))
            
    if message.content == '!myclass':                       #generates class message on command !myclass
        await message.channel.send('{}, you are a level {} {} {} with {}.'.format(message.author.mention,
                                   random.randint(1,20),*mytype.whatclass()))
    


    if message.content == '!myscore':                       #Displays user score from betgame on command !myscore
        config = configparser.ConfigParser()                #initialize configparser
        config.read('betgame.ini')
        if config['FIGHT']['fighting'] == 'True':           #check if fight happening currently, won't display score if it is
            await message.channel.send('Fight underway, wait until it\'s over.')
            return
        score = scorekeep.readscore(str(message.author))    #read score and display
        await message.channel.send('Your score is {}'.format(score))

    if message.content == '!fight':                         #Starts fight on command !fight
        scorekeep.fightgame()                               #Initialize configparser
        config = configparser.ConfigParser()
        config.read('betgame.ini')
        p1f = config['FIGHT']['p1f']                        #get variables generated by fightgame() and send fight message to channel
        p2f = config['FIGHT']['p2f']
        p1n = config['FIGHT']['p1n']
        p2n = config['FIGHT']['p2n']
        await message.channel.send('The {} is fighting the {}! ({}:{})'.format(p1f,p2f,p1n,p2n))
        im1 = Image.open('fight_image\{}.jpg'.format(p1f))  #generate fight image and send to channel
        vs = Image.open('fight_image\divider.jpg')
        im2 = Image.open('fight_image\{}.jpg'.format(p2f))
        im_list = [im1,vs,im2]
        multi_imageconcat(im_list).save('fightimage.jpg')
        await message.channel.send(file=discord.File('fightimage.jpg'))
        await asyncio.sleep(60)                             #wait for all bets to be in
        config.read('betgame.ini')                          #Reread because changes have been made from bets
        winner = config['FIGHT']['winner']                  #get winner from config
        await message.channel.send('The {} won!'.format(winner))
        config.set('FIGHT', 'winner', '')                   #clear variables from config file, not all of these are
        config.set('FIGHT', 'loser', '')                    #necessary in this build but they don't hurt
        config.set('FIGHT', 'p1f', '')
        config.set('FIGHT', 'p2f', '')
        config.set('FIGHT', 'p1n', '')
        config.set('FIGHT', 'p2n', '')
        config.set('FIGHT','betters','')
        config.set('FIGHT', 'fighting', 'False')            #end fight
        with open('betgame.ini', 'w+') as configfile:       #update config file
            config.write(configfile)
        
    if message.content.startswith('!bet'):                  #Submits bet during fight in formate !bet {fighter} {amount}
        config = configparser.ConfigParser()                #initialize configparser
        config.read('betgame.ini')
        betters = config['FIGHT']['betters']                #get betters from config and refuse bet if message author 
        if str(message.author) in betters:                  #already bet
            await message.add_reaction('👎')
            await asyncio.sleep(0.5)
            await message.channel.send('You already bet.')
            return
        if not config.has_option('USERS',str(message.author)):      #check if author is already stored in config
            await message.channel.send('Adding {}...'.format(message.author.mention)) #if not, add author using readscore()
            scorekeep.readscore(str(message.author))
        winner = config['FIGHT']['winner']                  #get winner and loser from config
        loser = config['FIGHT']['loser']
        if winner == '':                                    #if winner empty, no bets
            await message.channel.send('Fights done, go home.')
            return
        messlst = message.content.lower().split()           #split message.content into list ['!bet','{fighter}','{amount}']
        if len(messlst) != 3:                               #fail if too many words
            await message.add_reaction('👎')
            return
        if not messlst[2].isdigit():                        #fail if bet not a number
            await message.add_reaction('👎')
            return
        fighter = messlst[1]
        bet = int(messlst[2])
        currentscore = int(scorekeep.readscore(str(message.author))) #get message author current score
        if currentscore <= 0:                               #if author broke, give money
            currentscore = 1000
        if bet > currentscore:                              #fail if bet higher than money available
            await message.add_reaction('👎')
            return
        if bet <= 0:                                        #fail if bet < 0
            await message.add_reaction('👎')
            return
        if fighter != winner and fighter != loser:          #fail if fighter not fighting
            await message.add_reaction('👎')
            return
        await message.add_reaction('👍')                    #confirm succesful bet and add message author to betters 
        config.set('FIGHT','betters','{} {}'.format(config['FIGHT']['betters'], str(message.author)))
        with open('betgame.ini','w+') as configfile:
            config.write(configfile)
        if fighter == winner:                               #if bet on winner, add money based on odds, if not lose money
            p1f = config['FIGHT']['p1f']
            p2f = config['FIGHT']['p2f']
            p1n = int(config['FIGHT']['p1n'])
            p2n = int(config['FIGHT']['p2n'])
            if winner == p1f:
                scorekeep.writescore(str(message.author), currentscore + bet * (p2n/p1n))
            else:
                scorekeep.writescore(str(message.author), currentscore + bet * (p1n/p2n))            
        else:
            scorekeep.writescore(str(message.author), currentscore - bet)

    if message.content == '!lb':                            #displays leaderboard on command !lb
        config = configparser.ConfigParser()                #initialize configparser
        config.read('betgame.ini')
        if config['FIGHT']['fighting'] == 'True':           #Won't display if fighting
            await message.channel.send('Fight underway, wait until it\'s over.')
            return
        board = scorekeep.leaderboard()                     #get current leaderboard from config
        lbmess = ''                                         #generate leaderboard message
        for i in range(len(board)):
            tempstr = '{}. {} {}\n'.format(len(board)-i,board[i][0],board[i][1])
            lbmess += tempstr
        await message.channel.send(lbmess)
    
    if message.content == '!leohelp':                       #lists commands available in LeoBot on !leohelp
        helpmess = '!myaesthetic - assigns your aesthetic\n!mytype - assigns your Pokemon type\n!myscore - displays your current LeoBets score\n!fight - begins a LeoBets fight\n!bet {fighter} {amount} - places bet on LeoBets fight\n!leaderboard - displays current LeoBets leaderboard'
        await message.channel.send(helpmess)
        
        
        
        

client.run(token)




















